# init/playbooks/roles/ansible/tasks/configure.yml
- name: Ensure ansible group_vars directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_dir }}"
    - "{{ ansible_dir }}/group_vars/all"
    - "{{ ansible_dir }}/group_vars/termux"

- name: Copy ansible .vault_pass file
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/ansible/.vault_pass"
    dest: "{{ ansible_dir }}/.vault_pass"

- name: Copy ansible vault file
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/ansible/group_vars/all/vault.yaml"
    dest: "{{ termux_home }}/ansible/group_vars/all/vault.yaml"

- name: Re-encrypt vault file on target
  ansible.builtin.command:
    cmd: ansible-vault encrypt "{{ termux_home }}/ansible/group_vars/all/vault.yaml"
  environment:
    ANSIBLE_VAULT_PASSWORD_FILE: "{{ termux_home }}/ansible/.vault_pass"

- name: Genetate ansible.cfg
  ansible.builtin.ini_file:
    path: "{{ ansible_dir }}/ansible.cfg"
    mode: '0644'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: defaults, option: host_key_checking,   value: "false" }
    - { section: defaults, option: vault_password_file, value: "{{ ansible_dir }}/.vault_pass" }
    - { section: defaults, option: inventory,           value: "{{ ansible_dir }}/hosts.yaml" }
    - { section: defaults, option: collections_path,    value: "{{ ansible_dir }}/collections" }
    - { section: defaults, option: roles_path,          value: "{{ ansible_dir }}/roles" }
    - { section: ssh_connection, option: ssh_args,      value: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" }
    - { section: ssh_connection, option: pipelining,    value: "true" }
    - { section: privilege_escalation, option: become,        value: "true" }
    - { section: privilege_escalation, option: become_method, value: "sudo" }
