# init/playbooks/roles/ansible/tasks/install.yml
- name: Get Termux prefix
  shell: echo $PREFIX
  register: termux_env_prefix
  changed_when: false

- name: Встановити надійне дзеркало
  raw: |
    echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" \
      > $PREFIX/etc/apt/sources.list
    pkg update -y 2>/dev/null || true
  failed_when: false

- name: Встановити системні залежності та pre-compiled python пакети
  raw: >
    pkg install -y
    python python-pip python-cryptography
    git make cmake libsodium openssl libffi
    clang build-essential
  failed_when: false

- name: Get ANDROID_API level
  shell: getprop ro.build.version.sdk
  register: android_sdk
  changed_when: false

- name: Встановити Ansible
  shell: pip install ansible
  environment:
    LDFLAGS: "-L{{ termux_env_prefix.stdout }}/lib"
    CPPFLAGS: "-I{{ termux_env_prefix.stdout }}/include"
    ANDROID_API_LEVEL: "{{ android_sdk.stdout }}"